package AST;

import org.llvm.Value;

/* Generated By:JJTree: Do not edit this line. ASTarray.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTarray extends SimpleNode {
  public SimpleNode id, len;
  public ASTarray(int id) {
    super(id);
  }

  public ASTarray(MyLang p, int id) {
    super(p, id);
  }
  
  @Override
  public ASTArrayContent code_gen(ASTContext context) throws Exception {

		
    if (children == null)
    	throw new Exception("Unknown Exception in ASTArray.");
    id = (SimpleNode)children[0];
    len = children.length == 2 ? (SimpleNode)children[1]:null;
	Value arrayId = id.code_gen(context).value;
	String lengthOnjjt = (len != null) ? len.jjtGetValue().toString(): "-1";
	jjtSetValue(id.jjtGetValue()+":"+lengthOnjjt);
	
	Value val;
	if(len != null){
		Value length = len.code_gen(context).value;
		Value tmp = MyLang.module.addGlobal(ty_int, "tmp");
		tmp.setInitializer(ASTContent.getTypeZero(47));
		val = MyLang.builder.buildStore(length, tmp);
	} else val = null;
	
	int type = ARRAY;
	int info_type = DEFAULT;//still unknown
	//这个info_type应该在var_declaration结点被转化为数组真正的type(int/char/bool)
	return new ASTArrayContent(arrayId, type, info_type , val);
  }
}
/* JavaCC - OriginalChecksum=2cfbafd3f3f9e655aef8ad3b63fad655 (do not edit this line) */