package AST;

/* Generated By:JJTree: Do not edit this line. ASTbreakstm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTbreakstm extends SimpleNode {
  public ASTbreakstm(int id) {
    super(id);
  }

  public ASTbreakstm(MyLang p, int id) {
    super(p, id);
  }
  
  public ASTContent code_gen(ASTContext Context){
	  if (Context.breakBB == null){
		//  throw new Exception("break basicblock is null");
	  }
	  MyLang.builder.buildBr(Context.breakBB);
//	  BasicBlock anonyBB = MyLang.f_main.appendBasicBlock("after_break");
//	  MyLang.builder.positionBuilderAtEnd(anonyBB);
	  return null;
  }

}
/* JavaCC - OriginalChecksum=5755f44477223ad2dcbca987a427787c (do not edit this line) */
