package AST;
/* Generated By:JJTree: Do not edit this line. ASTblock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTblock extends SimpleNode {
  public ASTblock(int id) {
    super(id);
  }

  public ASTblock(MyLang p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=08ad6edee9ae3767302705a059232dde (do not edit this line) */
