package AST;
/* Generated By:JJTree: Do not edit this line. ASTcommonstm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTcommonstm extends SimpleNode {
  public ASTcommonstm(int id) {
    super(id);
  }

  public ASTcommonstm(MyLang p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5f6e279bf89f7ca285432df6a22f1602 (do not edit this line) */
