package AST;

/* Generated By:JJTree: Do not edit this line. ASTclass_declaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTclass_declaration extends SimpleNode {
	SimpleNode block;
  public ASTclass_declaration(int id) {
    super(id);
  }

  public ASTclass_declaration(MyLang p, int id) {
    super(p, id);
  }

  public ASTContent code_gen(ASTContext Context) throws Exception{
	  String className = ((SimpleNode) children[0]).jjtGetValue().toString();
	  SimpleNode field = this;
	  Context.put(className, field);
	  return null;
  }
}
/* JavaCC - OriginalChecksum=fc2e6f67d96484ae1f1440cedb3fc3a0 (do not edit this line) */
