package AST;
/* Generated By:JJTree: Do not edit this line. ASTcontinuestm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTcontinuestm extends SimpleNode {
  public ASTcontinuestm(int id) {
    super(id);
  }

  public ASTcontinuestm(MyLang p, int id) {
    super(p, id);
  }

  public ASTContent code_gen(ASTContext Context){
	  if (Context.continueBB == null){
		//  throw new Exception("break basicblock is null");
	  }
	  MyLang.builder.buildBr(Context.continueBB);
//	  BasicBlock anonyBB = MyLang.f_main.appendBasicBlock("after_break");
//	  MyLang.builder.positionBuilderAtEnd(anonyBB);
	  return null;
  }
}
/* JavaCC - OriginalChecksum=869380bb87c78605b717b9f6a8d5a979 (do not edit this line) */
