package AST;
/* Generated By:JJTree: Do not edit this line. ASTdeclaration_kind.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTdeclaration_kind extends SimpleNode {
  public ASTdeclaration_kind(int id) {
    super(id);
  }

  public ASTdeclaration_kind(MyLang p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a1d7eb2ffe0d662822dde086e196e704 (do not edit this line) */
