package AST;
import org.llvm.*;

/* Generated By:JJTree: Do not edit this line. ASTFloat.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFloat extends SimpleNode {
  public ASTFloat(int id) {
    super(id);
  }

  public ASTFloat(MyLang p, int id) {
    super(p, id);
  }
  
  public String toString(){
	  return "Float : "+ Double.valueOf(jjtGetValue().toString());
  }
  
  public ASTContent code_gen(ASTContext context){
	  double x = Double.valueOf(jjtGetValue().toString());
	  return new ASTContent(TypeRef.doubleType().constReal(x), FLOAT_LITERAL);
  }

}
/* JavaCC - OriginalChecksum=5cd5d5920ea97ebb407481087b54883d (do not edit this line) */