package AST;
import org.llvm.TypeRef;

/* Generated By:JJTree: Do not edit this line. ASTInteger.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTInteger extends SimpleNode {
  public ASTInteger(int id) {	  
    super(id);
  }

  public ASTInteger(MyLang p, int id) {
    super(p, id);
  }

  public ASTContent code_gen(ASTContext context) {
	  int x = Integer.valueOf(jjtGetValue().toString());
	  return new ASTContent(TypeRef.int32Type().constInt(x, true), INTEGER_LITERAL);
  }
}
/* JavaCC - OriginalChecksum=936c0d859d1c8f599bf17f80b014ddbf (do not edit this line) */
