package AST;
/* Generated By:JJTree: Do not edit this line. ASTNull.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNull extends SimpleNode {
  public ASTNull(int id) {
    super(id);
  }

  public ASTNull(MyLang p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7eb6faa3a1de354ad5d35abd73d53bc7 (do not edit this line) */
