package AST;
/* Generated By:JJTree: Do not edit this line. ASTPrimaryAccess.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPrimaryAccess extends SimpleNode {
  public ASTPrimaryAccess(int id) {
    super(id);
  }

  public ASTPrimaryAccess(MyLang p, int id) {
    super(p, id);
  }

	public ASTContent code_gen(ASTContext context) throws Exception 
	{
		char op = jjtGetValue().toString().charAt(0);
		switch (op) {
			case '(': return new ASTContent(null, FUNCTION);
			case '[': return new ASTContent(null, ARRAY);
			case '.': return  new ASTContent(null, CLASS);
			default: throw new Exception("Unknown access");
		}
	}
}
/* JavaCC - OriginalChecksum=5919d0b5d652450c94b93d9aec68b3b5 (do not edit this line) */
