package AST;
/* Generated By:JJTree: Do not edit this line. ASTprogram.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTprogram extends SimpleNode {
  public ASTprogram(int id) {
    super(id);
  }

  public ASTprogram(MyLang p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dfae686274bb77f3e506aa80f766572e (do not edit this line) */
