package AST;
/* Generated By:JJTree: Do not edit this line. ASTprimtype.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTprimtype extends SimpleNode {
  public ASTprimtype(int id) {
    super(id);
  }

  public ASTprimtype(MyLang p, int id) {
    super(p, id);
  }
  
  public ASTContent code_gen(ASTContext context) {
	  String name = jjtGetValue().toString();
	  switch (name.charAt(0)) {
	  case 'b':
		  return new ASTContent(null, TYPE, BOOLEAN_LITERAL);
	  case 'c':	 
		  return new ASTContent(null, TYPE, CHARACTER_LITERAL);
	  case 'i': 
		  return new ASTContent(null, TYPE, INTEGER_LITERAL);
	  case 'f':
		  return new ASTContent(null, TYPE, FLOAT_LITERAL);
	  case 'v':
		  return new ASTContent(null, TYPE, VOID);	
	  }
	return null;
  }
}
/* JavaCC - OriginalChecksum=08ceaad0c8fac97ca0b8726192c621ad (do not edit this line) */
