package AST;
/* Generated By:JJTree: Do not edit this line. ASTreturnstm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTreturnstm extends SimpleNode {
  public ASTreturnstm(int id) {
    super(id);
  }

  public ASTreturnstm(MyLang p, int id) {
    super(p, id);
  }

  public ASTContent code_gen(ASTContext context) throws Exception{
	//  op = jjtGetValue().toString();
	  int type = context.func.type;
	  SimpleNode exp = (SimpleNode)children[0];
	  ASTContent e = exp.code_gen(context);
	  if (e == null) return null;
	  return new ASTContent(MyLang.builder.buildRet(e.castTo(type)), type);
	}
}
/* JavaCC - OriginalChecksum=7a6ebf0e047dc8fdb8d6aeb3515b14b9 (do not edit this line) */
