package AST;
/* Generated By:JJTree: Do not edit this line. ASTstart.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTstart extends SimpleNode {
  public ASTstart(int id) {
    super(id);
  }

  public ASTstart(MyLang p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9a33cd687ce5bde7e4895c64ba8aa914 (do not edit this line) */
