package AST;
/* Generated By:JJTree: Do not edit this line. ASTString.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import org.llvm.*;

public
class ASTString extends SimpleNode implements MyLangConstants{
  public ASTString(int id) {
    super(id);
  }

  public ASTString(MyLang p, int id) {
    super(p, id);
  }

  public String toString() {
	  return "String : " + jjtGetValue().toString();
  }
  
  public ASTNewArrayContent code_gen(ASTContext context) throws Exception{
	  String str = jjtGetValue().toString();
	  str = str.substring(1, str.length()-1);
	  char[] chars = str.toCharArray();
	  Value tmp = MyLang.module.addGlobal(ty_int.arrayType(ty_int.type(), chars.length), str);
	  tmp.setInitializer(ASTContent.getTypeZero(CHARACTER_LITERAL));
	  for(int i = 0; i < chars.length; i++){
		  Value setter = MyLang.builder.buildInBoundsGEP(tmp, "tmp", ty_int.constInt(0, true),ty_int.constInt(i, true));
		  MyLang.builder.buildStore(TypeRef.int32Type().constInt(chars[i], true), setter);
	  }
	  ASTNewArrayContent newArray = new ASTNewArrayContent(tmp, ARRAY, CHARACTER_LITERAL, chars.length);
	  return newArray;
  }
}
/* JavaCC - OriginalChecksum=efce15c2569e57391670f9f13eaf6a97 (do not edit this line) */