package AST;
/* Generated By:JJTree: Do not edit this line. ASTType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTType extends SimpleNode {
  public ASTType(int id) {
    super(id);
  }

  public ASTType(MyLang p, int id) {
    super(p, id);
  }

  public ASTContent code_gen(ASTContext context) throws Exception {
	    if (children == null) return null;  
	    return  ((SimpleNode) children[0]).code_gen(context);
  }
}
/* JavaCC - OriginalChecksum=81a3ae20e8cb3f7633081ca08b0ee871 (do not edit this line) */
