package AST;
/* Generated By:JavaCC: Do not edit this line. MyLangTreeConstants.java Version 5.0 */
public interface MyLangTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROGRAM = 1;
  public int JJTBLOCK = 2;
  public int JJTVOID = 3;
  public int JJTIFTHENSTM = 4;
  public int JJTFOREACHSTM = 5;
  public int JJTCONTINUESTM = 6;
  public int JJTBREAKSTM = 7;
  public int JJTFORSTM = 8;
  public int JJTWHILESTM = 9;
  public int JJTRETURNSTM = 10;
  public int JJTCOMMONSTM = 11;
  public int JJTCLASS_DECLARATION = 12;
  public int JJTDECLARATION = 13;
  public int JJTFUNC_DECLARATION = 14;
  public int JJTVAR_DECLARATION = 15;
  public int JJTARRAY = 16;
  public int JJTTYPE = 17;
  public int JJTPRIMTYPE = 18;
  public int JJTARRAYCONSTRUCTOR = 19;
  public int JJTASSIGNMENT = 20;
  public int JJTLOGICALOREXPRESSION = 21;
  public int JJTLOGICALANDEXPRESSION = 22;
  public int JJTEQUALITYEXPRESSION = 23;
  public int JJTRELATIONALEXPRESSION = 24;
  public int JJTSHIFTEXPRESSION = 25;
  public int JJTOPT = 26;
  public int JJTCOMMONEXPRESSION = 27;
  public int JJTUNARYEXPRESSION = 28;
  public int JJTPRIMARYPREFIXACCESS = 29;
  public int JJTPRIMARYACCESS = 30;
  public int JJTIDENTIFIER = 31;
  public int JJTINTEGER = 32;
  public int JJTFLOAT = 33;
  public int JJTCHAR = 34;
  public int JJTBOOLEAN = 35;
  public int JJTNULL = 36;
  public int JJTSTRING = 37;


  public String[] jjtNodeName = {
    "start",
    "program",
    "block",
    "void",
    "ifthenstm",
    "foreachstm",
    "continuestm",
    "breakstm",
    "forstm",
    "whilestm",
    "returnstm",
    "commonstm",
    "class_declaration",
    "declaration",
    "func_declaration",
    "var_declaration",
    "array",
    "Type",
    "primtype",
    "ArrayConstructor",
    "Assignment",
    "LogicalOrExpression",
    "LogicalAndExpression",
    "EqualityExpression",
    "RelationalExpression",
    "ShiftExpression",
    "Opt",
    "CommonExpression",
    "UnaryExpression",
    "PrimaryPrefixAccess",
    "PrimaryAccess",
    "Identifier",
    "Integer",
    "Float",
    "Char",
    "Boolean",
    "Null",
    "String",
  };
}
/* JavaCC - OriginalChecksum=55014d7575d28f253338a75c77124bbf (do not edit this line) */
